Copystatic/admin/config.yml: copy code to clipboard
backend:
  name: github
  repo: xXValhallaCoderXx/tutorial-gatsby-netlify-blog
media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: content/blog-posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: featuredImage, label: Featured Image, widget: image }
      - { name: date, label: Date, widget: datetime }
      - { name: intro, label: Intro, widget: string }
      - { name: category, label: Category, widget: string }
      - { name: height, label: Height, widget: string }
      - { name: weight, label: Weight, widget: string }
      - { name: body, label: Body, widget: markdown }